/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bms.ui.investmentbank;

import com.bms.model.investmentbank.AccountProfile;
import com.bms.model.investmentbank.CompanyStock;
import com.bms.model.investmentbank.CurrencyStock;
import com.bms.model.investmentbank.StockProfile;
import static com.bms.ui.investmentbank.InvestmentMainJPanel.HISTORYFILEPATH;

import com.bms.model.investmentbank.CreateGraph;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.TextField;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingConstants;

/**
 *
 * @author asawari
 */
public class MakeInvestmentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MakeInvestmentJPanel
     */
    // CURRENCY STOCK TEXT FIELDS
    
    JTextField[][] textFields;
    JTextField[][] differenceTextFields;
    
    JTextArea stocksBoughtInfo;
    AccountProfile accProfile;
    StockProfile stocksProfiles;
    
    JPanel cards;
    CardLayout cl;
//    ButtonListener listener = new ButtonListener();
    
    
    
    public MakeInvestmentJPanel(JPanel cards,AccountProfile account, StockProfile profiles) {
        initComponents();
        accProfile = account;
        stocksProfiles = profiles;
        this.cards = cards;
        this.cl =  (CardLayout)cards.getLayout();

        //this.stocks1 = new StockProfile[8][8];
       
       textFields = new JTextField[2][4];
        differenceTextFields = new JTextField[2][4];
        
        textFields[0][0] = EURUSD;
        textFields[0][1] = GBPUSD;
        textFields[0][2] = EURGBP;
        textFields[0][3] = GBPJPY;
        
        differenceTextFields[0][0] = diffEURUSD;
        differenceTextFields[0][1] = diffGBPUSD;
        differenceTextFields[0][2] = diffEURGBP;
        differenceTextFields[0][3] = diffGBPJPY;
        
        textFields[1][0] = facebook;
        textFields[1][1] = apple;
        textFields[1][2] = microsoft;
        textFields[1][3] = bmw;
        
        differenceTextFields[1][0] = difffacebook;
        differenceTextFields[1][1] = diffapple;
        differenceTextFields[1][2] = diffmicrosoft;
        differenceTextFields[1][3] = diffbmw;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        currencyPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblEURUSD = new javax.swing.JLabel();
        lblGBPUSD = new javax.swing.JLabel();
        lblEURGBP = new javax.swing.JLabel();
        lblGBPJPY = new javax.swing.JLabel();
        EURUSD = new javax.swing.JTextField();
        GBPUSD = new javax.swing.JTextField();
        EURGBP = new javax.swing.JTextField();
        GBPJPY = new javax.swing.JTextField();
        diffEURUSD = new javax.swing.JTextField();
        diffGBPJPY = new javax.swing.JTextField();
        diffGBPUSD = new javax.swing.JTextField();
        diffEURGBP = new javax.swing.JTextField();
        companyPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblfacebook = new javax.swing.JLabel();
        lblapple = new javax.swing.JLabel();
        lblmicrosoft = new javax.swing.JLabel();
        lblbmw = new javax.swing.JLabel();
        facebook = new javax.swing.JTextField();
        apple = new javax.swing.JTextField();
        microsoft = new javax.swing.JTextField();
        bmw = new javax.swing.JTextField();
        difffacebook = new javax.swing.JTextField();
        diffapple = new javax.swing.JTextField();
        diffmicrosoft = new javax.swing.JTextField();
        diffbmw = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnShowGraph = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        viewProfileLbl = new javax.swing.JLabel();
        homePanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        viewAccountsLbl = new javax.swing.JLabel();
        homePanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        makeTransactionsLbl = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        homePanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        investLbl1 = new javax.swing.JLabel();
        names = new javax.swing.JComboBox<>();
        lblshareName = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel1.setText("Currency Stock");

        lblEURUSD.setText("EUR/USD:");

        lblGBPUSD.setText("GBP/USD:");

        lblEURGBP.setText("EUR/GBP:");

        lblGBPJPY.setText("GBP/JPY:");

        javax.swing.GroupLayout currencyPanelLayout = new javax.swing.GroupLayout(currencyPanel);
        currencyPanel.setLayout(currencyPanelLayout);
        currencyPanelLayout.setHorizontalGroup(
            currencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currencyPanelLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel1)
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, currencyPanelLayout.createSequentialGroup()
                .addGroup(currencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(currencyPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(diffGBPUSD, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(currencyPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(currencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblGBPUSD)
                            .addComponent(lblEURUSD)
                            .addComponent(lblEURGBP)
                            .addComponent(lblGBPJPY))
                        .addGap(31, 31, 31)
                        .addGroup(currencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GBPUSD)
                            .addComponent(EURGBP)
                            .addComponent(GBPJPY)
                            .addComponent(EURUSD, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(currencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(currencyPanelLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(diffEURUSD, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, currencyPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(currencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(diffEURGBP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(diffGBPJPY, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(42, 42, 42))
        );
        currencyPanelLayout.setVerticalGroup(
            currencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currencyPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(currencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(currencyPanelLayout.createSequentialGroup()
                        .addComponent(diffEURUSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(diffGBPUSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(diffEURGBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(diffGBPJPY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(currencyPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(currencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEURUSD)
                            .addComponent(EURUSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(currencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGBPUSD)
                            .addComponent(GBPUSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(currencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEURGBP)
                            .addComponent(EURGBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(currencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGBPJPY)
                            .addComponent(GBPJPY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel2.setText("Company Stock");

        lblfacebook.setText("Facebook:");

        lblapple.setText("Apple:");

        lblmicrosoft.setText("Microsoft:");

        lblbmw.setText("BMW:");

        bmw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmwActionPerformed(evt);
            }
        });

        diffbmw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diffbmwActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout companyPanelLayout = new javax.swing.GroupLayout(companyPanel);
        companyPanel.setLayout(companyPanelLayout);
        companyPanelLayout.setHorizontalGroup(
            companyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(companyPanelLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(companyPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(companyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblfacebook)
                    .addComponent(lblapple)
                    .addComponent(lblmicrosoft)
                    .addComponent(lblbmw))
                .addGap(47, 47, 47)
                .addGroup(companyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(companyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(microsoft, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                        .addComponent(bmw)
                        .addComponent(apple))
                    .addComponent(facebook, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(companyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(companyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(difffacebook, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                        .addComponent(diffapple)
                        .addComponent(diffbmw))
                    .addComponent(diffmicrosoft, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        companyPanelLayout.setVerticalGroup(
            companyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(companyPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(companyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(companyPanelLayout.createSequentialGroup()
                        .addGroup(companyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblfacebook)
                            .addComponent(facebook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(companyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblapple)
                            .addComponent(apple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(companyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblmicrosoft)
                            .addComponent(microsoft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(companyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblbmw)
                            .addComponent(bmw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(companyPanelLayout.createSequentialGroup()
                        .addComponent(difffacebook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(diffapple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(diffmicrosoft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(diffbmw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(currencyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(companyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(companyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(currencyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel11.setText("Stock Simulator");

        btnShowGraph.setBackground(new java.awt.Color(25, 33, 39));
        btnShowGraph.setForeground(new java.awt.Color(255, 255, 255));
        btnShowGraph.setText("View Graph");
        btnShowGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowGraphActionPerformed(evt);
            }
        });

        mainPanel.setBackground(new java.awt.Color(122, 72, 221));

        homePanel.setBackground(new java.awt.Color(54, 33, 39));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bms/UI/images/login.png"))); // NOI18N

        viewProfileLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        viewProfileLbl.setForeground(new java.awt.Color(255, 255, 255));
        viewProfileLbl.setText("Profile");
        viewProfileLbl.setToolTipText("");
        viewProfileLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewProfileLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewProfileLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
            .addComponent(viewProfileLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        homePanel1.setBackground(new java.awt.Color(54, 33, 39));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bms/UI/images/search.png"))); // NOI18N

        viewAccountsLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        viewAccountsLbl.setForeground(new java.awt.Color(255, 255, 255));
        viewAccountsLbl.setText("View Accounts");
        viewAccountsLbl.setToolTipText("");
        viewAccountsLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewAccountsLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout homePanel1Layout = new javax.swing.GroupLayout(homePanel1);
        homePanel1.setLayout(homePanel1Layout);
        homePanel1Layout.setHorizontalGroup(
            homePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewAccountsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        homePanel1Layout.setVerticalGroup(
            homePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(viewAccountsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        homePanel2.setBackground(new java.awt.Color(54, 33, 39));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bms/UI/images/money.png"))); // NOI18N

        makeTransactionsLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        makeTransactionsLbl.setForeground(new java.awt.Color(255, 255, 255));
        makeTransactionsLbl.setText("Withdraw/Deposit");
        makeTransactionsLbl.setToolTipText("");
        makeTransactionsLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                makeTransactionsLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout homePanel2Layout = new javax.swing.GroupLayout(homePanel2);
        homePanel2.setLayout(homePanel2Layout);
        homePanel2Layout.setHorizontalGroup(
            homePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(makeTransactionsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        homePanel2Layout.setVerticalGroup(
            homePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(homePanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(makeTransactionsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Welcome Customer!");
        jLabel10.setToolTipText("");

        homePanel3.setBackground(new java.awt.Color(54, 33, 39));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bms/UI/images/money.png"))); // NOI18N

        investLbl1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        investLbl1.setForeground(new java.awt.Color(255, 255, 255));
        investLbl1.setText("Investment Banking");
        investLbl1.setToolTipText("");
        investLbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                investLbl1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout homePanel3Layout = new javax.swing.GroupLayout(homePanel3);
        homePanel3.setLayout(homePanel3Layout);
        homePanel3Layout.setHorizontalGroup(
            homePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(investLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        homePanel3Layout.setVerticalGroup(
            homePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(homePanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(investLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(homePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(homePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(homePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(homePanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(381, 381, 381)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(homePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(homePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(homePanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(homePanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        names.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EUR-USD", "GBP-USD", "EUR-GBP", "GBP-JPY", "Facebook", "Apple", "Microsoft", "BMW" }));

        lblshareName.setText("Share Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(234, 234, 234)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(409, 409, 409)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(399, 399, 399)
                                .addComponent(lblshareName)
                                .addGap(33, 33, 33)
                                .addComponent(names, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(441, 441, 441)
                .addComponent(btnShowGraph)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblshareName)
                    .addComponent(names, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(btnShowGraph)
                .addGap(143, 143, 143)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bmwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bmwActionPerformed

    private void diffbmwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diffbmwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diffbmwActionPerformed

    private void btnShowGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowGraphActionPerformed
        // TODO add your handling code here:
             String fileName = (String) names.getSelectedItem();

             CreateGraph graph = new CreateGraph(fileName);
                
            //ViewGraph graph = new ViewGraph(stocksProfiles);
            //cards.add(graph, "VGPanel");
            //cl.addLayoutComponent(this, SOMEBITS);
            //splitPane.setRightComponent(cards);
            //cl.show(cards, "VGPanel");
                
    }//GEN-LAST:event_btnShowGraphActionPerformed

    private void viewProfileLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewProfileLblMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_viewProfileLblMouseClicked

    private void viewAccountsLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAccountsLblMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_viewAccountsLblMouseClicked

    private void makeTransactionsLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_makeTransactionsLblMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_makeTransactionsLblMouseClicked

    private void investLbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_investLbl1MouseClicked



    }//GEN-LAST:event_investLbl1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EURGBP;
    private javax.swing.JTextField EURUSD;
    private javax.swing.JTextField GBPJPY;
    private javax.swing.JTextField GBPUSD;
    private javax.swing.JTextField apple;
    private javax.swing.JTextField bmw;
    private javax.swing.JButton btnShowGraph;
    private javax.swing.JPanel companyPanel;
    private javax.swing.JPanel currencyPanel;
    private javax.swing.JTextField diffEURGBP;
    private javax.swing.JTextField diffEURUSD;
    private javax.swing.JTextField diffGBPJPY;
    private javax.swing.JTextField diffGBPUSD;
    private javax.swing.JTextField diffapple;
    private javax.swing.JTextField diffbmw;
    private javax.swing.JTextField difffacebook;
    private javax.swing.JTextField diffmicrosoft;
    private javax.swing.JTextField facebook;
    private javax.swing.JPanel homePanel;
    private javax.swing.JPanel homePanel1;
    private javax.swing.JPanel homePanel2;
    private javax.swing.JPanel homePanel3;
    private javax.swing.JLabel investLbl1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblEURGBP;
    private javax.swing.JLabel lblEURUSD;
    private javax.swing.JLabel lblGBPJPY;
    private javax.swing.JLabel lblGBPUSD;
    private javax.swing.JLabel lblapple;
    private javax.swing.JLabel lblbmw;
    private javax.swing.JLabel lblfacebook;
    private javax.swing.JLabel lblmicrosoft;
    private javax.swing.JLabel lblshareName;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel makeTransactionsLbl;
    private javax.swing.JTextField microsoft;
    private javax.swing.JComboBox<String> names;
    private javax.swing.JLabel viewAccountsLbl;
    private javax.swing.JLabel viewProfileLbl;
    // End of variables declaration//GEN-END:variables
   
    
    // Method to set the values of the text boxes with the stock prices
    public void setTextBoxValues(StockProfile[][] stocksProfiles) {
        System.out.println("inside setTextBoxValues ");
        for (int i = 0; i < stocksProfiles.length; i++) {
            for (int j = 0; j < stocksProfiles[i].length; j++) {
                System.out.println("inside setTextBoxValues - for loop");
                StockProfile stock = stocksProfiles[i][j];

                setStockPriceTextField(textFields[i][j], stock);
                setDifferenceTextField(differenceTextFields[i][j], stock.getChange());
                setTextFieldColour(differenceTextFields[i][j], stock.getChange());

                writeRateToFile(stock.getProfileName(), stock.getBuyPrice());

            }
        }

        //setStockBought();

    }

    // Method to set the buy and sell rates for a stock
    public void setStockPriceTextField(JTextField field, StockProfile profile) {
        field.setText(
                String.valueOf(profile.getBuyPrice()) + "/" + String.valueOf(profile.getSellPrice()));

    }

    // Setting the difference between current rate and previous rates
    public void setDifferenceTextField(JTextField field, double change) {
        String difference = (change > 0) ? ("+" + change) : ("" + change);
        field.setText(difference + "%");
    }

    //* Method to display the bought stocks in the relative text area
    public void setStockBought() {
        System.out.println("inside setStockBought()");
        ArrayList<StockProfile> stocksBought = accProfile.getStocks();
        System.out.println("inside setStockBought()"+accProfile);
        int numOfStock = stocksBought.size();
        System.out.println("inside setStockBought()--2");
        String message = "STOCK NAME - BUY PRICE/SELL PRICE - Quantity\n";

        for (int i = 0; i < numOfStock; i++) {
            System.out.println("inside setStockBought()--for loop to display message");
            message = message + stocksBought.get(i).getProfileName() + " - " + stocksBought.get(i).getBuyPrice() + "/"
                    + stocksBought.get(i).getSellPrice() + " - " + stocksBought.get(i).getQuantity() + "\n";
        }
        
        message = message + "\nBALANCE: " + roundTo2DP(accProfile.getBalance());
        System.out.println("inside setStockBought()--to display balance");
        stocksBoughtInfo.setText(message);
    }
    
    // Method to set the font colour of the difference
    public void setTextFieldColour(JTextField field, double change) {
        if (change >= 0) {
            field.setForeground(Color.green);
        } else {
            field.setForeground(Color.red);
        }
    }

    // Method to write the rate to its relavant file
    public void writeRateToFile(String fileName, double rate) {

        try {
            String location = HISTORYFILEPATH + fileName + ".csv";

            Calendar getTime = Calendar.getInstance();
            SimpleDateFormat formatTime = new SimpleDateFormat("HH:mm:ss");
            String timeStamp = formatTime.format(getTime.getTime());

            try (BufferedWriter write = new BufferedWriter(new FileWriter(location, true))) {
                String lineToWrite = timeStamp + "," + rate;
                write.write(lineToWrite);

                write.newLine();
            }
        } catch (IOException e) {
            System.out.println("Error: " + e);
        }
        
    }  
       
    // Rounding to 2 decimal place
    public static Double roundTo2DP(double number) {
        DecimalFormat roundFormat = new DecimalFormat(".##");
         return (Double.parseDouble(roundFormat.format(number)));
    }
    
    // Method that called when user wants to buy a stock
    public void buyStock(StockProfile profile, int quantity) {
        double price = profile.getBuyPrice() * quantity;
        
        if (price < accProfile.getBalance()) {
            StockProfile stock = new StockProfile(profile.getProfileName(),
                    profile.getSellPrice(), profile.getBuyPrice(), quantity);
            accProfile.setBalance(-price);
            accProfile.addStock(stock);

            displayNewBalance();

        } else {
            JOptionPane.showMessageDialog(null, "You Don't Have Enough Money", "ERROR",
                    JOptionPane.WARNING_MESSAGE);

        }

    }
    
    // Method that is called when user wants to sell a stock
    public void sellStock(StockProfile profile, int quantity, String stockName) {

        if (quantity <= profile.getQuantity()) {

            double price = profile.getSellPrice() * quantity;
            accProfile.setBalance(+price);
            if (quantity == profile.getQuantity()) {
                accProfile.removeStock(profile);
            } else {
                profile.setQuantity(profile.getQuantity() - quantity);
            }

            displayNewBalance();

        } else {
            JOptionPane.showMessageDialog(null, "You Do Not Own This Many Stock", "Error",
                    JOptionPane.WARNING_MESSAGE);
        }

    }
    
    //Method to display new balance
    public void displayNewBalance(){
        JOptionPane.showMessageDialog(null, "Balance: " + roundTo2DP(accProfile.getBalance()),
                    "Successful Sell", JOptionPane.WARNING_MESSAGE);
    }

    // Method to search account profile for a stock (used when user is selling stock)
    public StockProfile searchBoughtStock(String stockName) {
        ArrayList<StockProfile> stocksBought = accProfile.getStocks();
        for (int i = 0; i < stocksBought.size(); i++) {
            if (stocksBought.get(i).getProfileName().equalsIgnoreCase(stockName)) {
                return stocksBought.get(i);
            }
        }
        return null;
    }

    // Method to search  for a stock (used when user is buying stock)
    public StockProfile searchAvailableStock(String stockName) {
       
        //for (StockProfile[] stockArray : stocks1) {
            //System.out.println("inside searchAvailableStock- for loop"+ stockArray);
            //for (StockProfile stocks : stocksProfiles) {
                if (stocksProfiles.getProfileName().equalsIgnoreCase(stockName)) {

                    return stocksProfiles;
                    
                }
                System.out.println("inside searchAvailableStock- 2nd for loop");
            //}

        //}
        return null;
    }
 
  
    
}
    
 




    

