/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bms.ui;

import javax.swing.JOptionPane;

/**
 *
 * @author asawari
 */
public class LoanJFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoanJFrame
     */
    
    double loan;
    double interestRate;
    double month;
    double payment;
    double MonthlyPayment;
    
    public LoanJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtLoan = new javax.swing.JTextField();
        jTxtInterest = new javax.swing.JTextField();
        jTxtNoPayment = new javax.swing.JTextField();
        jTextMonthlyPayment = new javax.swing.JTextField();
        jLoanBtnLoanCalculator = new javax.swing.JButton();
        jLoanbtnReset = new javax.swing.JButton();
        jLoanBtnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLoanReport = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("Monthly EMI predictor");

        jLabel2.setText("Amount of loan:");

        jLabel3.setText("Interest Rate:");

        jLabel4.setText("Number of Payments:");

        jLabel5.setText("Monthly Payment:");

        jLoanBtnLoanCalculator.setText("Loan Calculator");
        jLoanBtnLoanCalculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoanBtnLoanCalculatorActionPerformed(evt);
            }
        });

        jLoanbtnReset.setText("Reset");
        jLoanbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoanbtnResetActionPerformed(evt);
            }
        });

        jLoanBtnExit.setText("Exit");
        jLoanBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoanBtnExitActionPerformed(evt);
            }
        });

        jLoanReport.setColumns(20);
        jLoanReport.setRows(5);
        jScrollPane1.setViewportView(jLoanReport);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jLoanBtnLoanCalculator)))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLoanbtnReset)
                                .addGap(70, 70, 70)
                                .addComponent(jLoanBtnExit))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTxtLoan, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                    .addComponent(jTxtInterest)
                                    .addComponent(jTxtNoPayment)
                                    .addComponent(jTextMonthlyPayment))
                                .addGap(42, 42, 42)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTxtLoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTxtInterest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTxtNoPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextMonthlyPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLoanBtnLoanCalculator)
                    .addComponent(jLoanbtnReset)
                    .addComponent(jLoanBtnExit))
                .addContainerGap(174, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLoanBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoanBtnExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLoanBtnExitActionPerformed

    private void jLoanBtnLoanCalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoanBtnLoanCalculatorActionPerformed
        // TODO add your handling code here:
 
        String monthlyPayment = String.format(jTextMonthlyPayment.getText());
        
        if (jTxtLoan.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter loan amount to borrow","Loan System", JOptionPane.INFORMATION_MESSAGE );
        }
        
        else
        {
            loan = Double.parseDouble(jTxtLoan.getText());
            String amount = String.format(jTxtLoan.getText());
        }
        
        ///////////////////////////////////////////
        if (jTxtInterest.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter Interest rate","Loan System", JOptionPane.INFORMATION_MESSAGE );
        }
        
        else
        {
            interestRate = Double.parseDouble(jTxtInterest.getText());
            String interest = String.format(jTxtInterest.getText());
        }
        
        //////////////////////////////////////////
        if (jTxtNoPayment.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter number of Installments","Loan System", JOptionPane.INFORMATION_MESSAGE );
        }
        
        else
        {
            month = Double.parseDouble(jTxtNoPayment.getText());
            String numberInstallement = String.format(jTxtNoPayment.getText());
        }
        //////////////////////////////////////////
        
        payment = loan + ((loan * interestRate)/ 100); 
        
        MonthlyPayment = (payment/month);
        String PayMonth = String.format("%.2f",MonthlyPayment);
        jTextMonthlyPayment.setText(PayMonth);
        
        jLoanReport.append("\tLoan Predictor:\n\n"+ 
        "Amount of Loan:\t\t" + loan 
        + "\nInterest Rate:\t\t" + interestRate 
        + "\nNumber of Installments:\t\t" + month 
        + "\nTotal Loan Payment:\t\t" + payment
        );
        
    }//GEN-LAST:event_jLoanBtnLoanCalculatorActionPerformed

    private void jLoanbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoanbtnResetActionPerformed
        // TODO add your handling code here:
        jTxtLoan.setText("");
        jTxtInterest.setText("");
        jTxtNoPayment.setText("");
        jTextMonthlyPayment.setText("");
    }//GEN-LAST:event_jLoanbtnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jLoanBtnExit;
    private javax.swing.JButton jLoanBtnLoanCalculator;
    private javax.swing.JTextArea jLoanReport;
    private javax.swing.JButton jLoanbtnReset;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextMonthlyPayment;
    private javax.swing.JTextField jTxtInterest;
    private javax.swing.JTextField jTxtLoan;
    private javax.swing.JTextField jTxtNoPayment;
    // End of variables declaration//GEN-END:variables
}
