/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bms.UI.employeerole;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ashwini
 */
public class LoanEstimatorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoanEstimatorJPanel
     */
    double loan;
    double interestRate;
    double month;
    double payment;
    double MonthlyPayment;
    JPanel cards;
    CardLayout cl;
    
    public LoanEstimatorJPanel(JPanel cards) {
        this.cards = cards;
        this.cl = (CardLayout) cards.getLayout();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtLoan = new javax.swing.JTextField();
        jTxtInterest = new javax.swing.JTextField();
        jTxtNoPayment = new javax.swing.JTextField();
        jTextMonthlyPayment = new javax.swing.JTextField();
        jLoanBtnLoanCalculator = new javax.swing.JButton();
        jLoanbtnReset = new javax.swing.JButton();
        jLoanBtnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLoanReport = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        mainPanel.setBackground(new java.awt.Color(122, 72, 221));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Monthly EMI Predictor");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jLabel2.setText("Amount of loan:");

        jLabel3.setText("Interest Rate:");

        jLabel4.setText("Number of Payments:");

        jLabel5.setText("Monthly Payment:");

        jLoanBtnLoanCalculator.setText("Loan Calculator");
        jLoanBtnLoanCalculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoanBtnLoanCalculatorActionPerformed(evt);
            }
        });

        jLoanbtnReset.setText("Reset");
        jLoanbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoanbtnResetActionPerformed(evt);
            }
        });

        jLoanBtnExit.setText("Exit");
        jLoanBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoanBtnExitActionPerformed(evt);
            }
        });

        jLoanReport.setColumns(20);
        jLoanReport.setRows(5);
        jScrollPane1.setViewportView(jLoanReport);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)))
                    .addComponent(jLoanBtnLoanCalculator))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLoanbtnReset)
                        .addGap(70, 70, 70)
                        .addComponent(jLoanBtnExit))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtLoan)
                            .addComponent(jTxtInterest)
                            .addComponent(jTxtNoPayment)
                            .addComponent(jTextMonthlyPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTxtLoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTxtInterest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTxtNoPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextMonthlyPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLoanBtnLoanCalculator)
                    .addComponent(jLoanbtnReset)
                    .addComponent(jLoanBtnExit))
                .addContainerGap(110, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLoanBtnLoanCalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoanBtnLoanCalculatorActionPerformed
        // TODO add your handling code here:

        String monthlyPayment = String.format(jTextMonthlyPayment.getText());

        if (jTxtLoan.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter loan amount to borrow","Loan System", JOptionPane.INFORMATION_MESSAGE );
        }

        else
        {
            loan = Double.parseDouble(jTxtLoan.getText());
            String amount = String.format(jTxtLoan.getText());
        }

        ///////////////////////////////////////////
        if (jTxtInterest.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter Interest rate","Loan System", JOptionPane.INFORMATION_MESSAGE );
        }

        else
        {
            interestRate = Double.parseDouble(jTxtInterest.getText());
            String interest = String.format(jTxtInterest.getText());
        }

        //////////////////////////////////////////
        if (jTxtNoPayment.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter number of Installments","Loan System", JOptionPane.INFORMATION_MESSAGE );
        }

        else
        {
            month = Double.parseDouble(jTxtNoPayment.getText());
            String numberInstallement = String.format(jTxtNoPayment.getText());
        }
        //////////////////////////////////////////

        payment = loan + ((loan * interestRate)/ 100);

        MonthlyPayment = (payment/month);
        String PayMonth = String.format("%.2f",MonthlyPayment);
        jTextMonthlyPayment.setText(PayMonth);

        jLoanReport.append("\tLoan Predictor:\n\n"+
            "Amount of Loan:\t\t" + loan
            + "\nInterest Rate:\t\t" + interestRate
            + "\nNumber of Installments:\t\t" + month
            + "\nTotal Loan Payment:\t\t" + payment
        );

    }//GEN-LAST:event_jLoanBtnLoanCalculatorActionPerformed

    private void jLoanbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoanbtnResetActionPerformed
        // TODO add your handling code here:
        jTxtLoan.setText("");
        jTxtInterest.setText("");
        jTxtNoPayment.setText("");
        jTextMonthlyPayment.setText("");
    }//GEN-LAST:event_jLoanbtnResetActionPerformed

    private void jLoanBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoanBtnExitActionPerformed
        // TODO add your handling code here:
        cl.previous(cards);
    }//GEN-LAST:event_jLoanBtnExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jLoanBtnExit;
    private javax.swing.JButton jLoanBtnLoanCalculator;
    private javax.swing.JTextArea jLoanReport;
    private javax.swing.JButton jLoanbtnReset;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextMonthlyPayment;
    private javax.swing.JTextField jTxtInterest;
    private javax.swing.JTextField jTxtLoan;
    private javax.swing.JTextField jTxtNoPayment;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
